spring:
  application:
    name: aop-demo

  redis:
    host: localhost
    password:
    port: 6379
    ttl: 60 # seconds

bookmark:
  mode: fs # fs and omitted for filesystem, otherwise redis
  root:
    folder: /tmp/bookmark/demo
  maxRetry: 3

# FS 33 SEC
# REDIS 229 SEC
