spring:
  application:
    name: aop-demo

  redis:
    host: localhost
    password:
    port: 6379

bookmark:
  mode: fs # fs and omitted for filesystem, otherwise redis
  root:
    folder: /tmp/bookmark/demo
  maxRetry: 3

